// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLtxqq3DicHPEGiSRBhYNJclfLVV1hgzY',
    appId: '1:435450589544:web:ef6f280d142a57f1f0e6dd',
    messagingSenderId: '435450589544',
    projectId: 'lost-in-egypt-elasly',
    authDomain: 'lost-in-egypt-elasly.firebaseapp.com',
    storageBucket: 'lost-in-egypt-elasly.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpLn2UsR773pvIN6uVUSWEL_MXwPNqzSw',
    appId: '1:435450589544:android:3ec27d857a05cca1f0e6dd',
    messagingSenderId: '435450589544',
    projectId: 'lost-in-egypt-elasly',
    storageBucket: 'lost-in-egypt-elasly.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaXz56Nl2wvYfgfHASi5SkWgtXLBZUTec',
    appId: '1:435450589544:ios:31a31fd75d91234bf0e6dd',
    messagingSenderId: '435450589544',
    projectId: 'lost-in-egypt-elasly',
    storageBucket: 'lost-in-egypt-elasly.firebasestorage.app',
    iosBundleId: 'com.example.lostInEgypt',
  );
}
